/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public class DRegisterCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DRegisterCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DRegisterCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tinyWRAPJNI.delete_DRegisterCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    tinyWRAPJNI.DRegisterCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    tinyWRAPJNI.DRegisterCallback_change_ownership(this, swigCPtr, true);
  }

  public DRegisterCallback() {
    this(tinyWRAPJNI.new_DRegisterCallback(), true);
    tinyWRAPJNI.DRegisterCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public int onAuthRegister(String message) {
    return (getClass() == DRegisterCallback.class) ? tinyWRAPJNI.DRegisterCallback_onAuthRegister(swigCPtr, this, message) : tinyWRAPJNI.DRegisterCallback_onAuthRegisterSwigExplicitDRegisterCallback(swigCPtr, this, message);
  }

}
