/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public class McpttCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected McpttCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(McpttCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tinyWRAPJNI.delete_McpttCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    tinyWRAPJNI.McpttCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    tinyWRAPJNI.McpttCallback_change_ownership(this, swigCPtr, true);
  }

  public McpttCallback() {
    this(tinyWRAPJNI.new_McpttCallback(), true);
    tinyWRAPJNI.McpttCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public int OnEvent(McpttEvent e) {
    return (getClass() == McpttCallback.class) ? tinyWRAPJNI.McpttCallback_OnEvent(swigCPtr, this, McpttEvent.getCPtr(e), e) : tinyWRAPJNI.McpttCallback_OnEventSwigExplicitMcpttCallback(swigCPtr, this, McpttEvent.getCPtr(e), e);
  }

}
