/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public class McpttMbmsMessage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected McpttMbmsMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(McpttMbmsMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tinyWRAPJNI.delete_McpttMbmsMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public McpttMbmsMessage() {
    this(tinyWRAPJNI.new_McpttMbmsMessage(), true);
  }

  public String getGroupId() {
    return tinyWRAPJNI.McpttMbmsMessage_getGroupId(swigCPtr, this);
  }

  public String getTMGI() {
    return tinyWRAPJNI.McpttMbmsMessage_getTMGI(swigCPtr, this);
  }

  public String getMediaIP() {
    return tinyWRAPJNI.McpttMbmsMessage_getMediaIP(swigCPtr, this);
  }

  public short getMediaPort() {
    return tinyWRAPJNI.McpttMbmsMessage_getMediaPort(swigCPtr, this);
  }

  public short getMediaControlPort() {
    return tinyWRAPJNI.McpttMbmsMessage_getMediaControlPort(swigCPtr, this);
  }

}
