/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public class McpttSession extends InviteSession {
  private long swigCPtr;

  protected McpttSession(long cPtr, boolean cMemoryOwn) {
    super(tinyWRAPJNI.McpttSession_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(McpttSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tinyWRAPJNI.delete_McpttSession(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public McpttSession(SipStack pStack, McpttCallback pCallback) {
    this(tinyWRAPJNI.new_McpttSession(SipStack.getCPtr(pStack), pStack, McpttCallback.getCPtr(pCallback), pCallback), true);
  }

  public boolean setCallback(McpttCallback pCallback) {
    return tinyWRAPJNI.McpttSession_setCallback(swigCPtr, this, McpttCallback.getCPtr(pCallback), pCallback);
  }

  public boolean requestToken(ActionConfig config) {
    return tinyWRAPJNI.McpttSession_requestToken__SWIG_0(swigCPtr, this, ActionConfig.getCPtr(config), config);
  }

  public boolean requestToken() {
    return tinyWRAPJNI.McpttSession_requestToken__SWIG_1(swigCPtr, this);
  }

}
