/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public class MessagingLocationEvent extends SipEvent {
  private long swigCPtr;

  protected MessagingLocationEvent(long cPtr, boolean cMemoryOwn) {
    super(tinyWRAPJNI.MessagingLocationEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MessagingLocationEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tinyWRAPJNI.delete_MessagingLocationEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public tsip_message_event_type_t getType() {
    return tsip_message_event_type_t.swigToEnum(tinyWRAPJNI.MessagingLocationEvent_getType(swigCPtr, this));
  }

  public MessagingLocationSession getSession() {
    long cPtr = tinyWRAPJNI.MessagingLocationEvent_getSession(swigCPtr, this);
    return (cPtr == 0) ? null : new MessagingLocationSession(cPtr, false);
  }

  public MessagingLocationSession takeSessionOwnership() {
    long cPtr = tinyWRAPJNI.MessagingLocationEvent_takeSessionOwnership(swigCPtr, this);
    return (cPtr == 0) ? null : new MessagingLocationSession(cPtr, true);
  }

}
