/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public class PublicationAffiliationEvent extends SipEvent {
  private long swigCPtr;

  protected PublicationAffiliationEvent(long cPtr, boolean cMemoryOwn) {
    super(tinyWRAPJNI.PublicationAffiliationEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PublicationAffiliationEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tinyWRAPJNI.delete_PublicationAffiliationEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public tsip_publish_event_type_t getType() {
    return tsip_publish_event_type_t.swigToEnum(tinyWRAPJNI.PublicationAffiliationEvent_getType(swigCPtr, this));
  }

  public PublicationAffiliationSession getSession() {
    long cPtr = tinyWRAPJNI.PublicationAffiliationEvent_getSession(swigCPtr, this);
    return (cPtr == 0) ? null : new PublicationAffiliationSession(cPtr, false);
  }

  public PublicationAffiliationSession takeSessionOwnership() {
    long cPtr = tinyWRAPJNI.PublicationAffiliationEvent_takeSessionOwnership(swigCPtr, this);
    return (cPtr == 0) ? null : new PublicationAffiliationSession(cPtr, true);
  }

}
