/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public class RegistrationAuthenticationEvent extends SipEvent {
  private long swigCPtr;

  protected RegistrationAuthenticationEvent(long cPtr, boolean cMemoryOwn) {
    super(tinyWRAPJNI.RegistrationAuthenticationEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RegistrationAuthenticationEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tinyWRAPJNI.delete_RegistrationAuthenticationEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public tsip_register_authentication_event_type_t getType() {
    return tsip_register_authentication_event_type_t.swigToEnum(tinyWRAPJNI.RegistrationAuthenticationEvent_getType(swigCPtr, this));
  }

}
