/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public class SubscriptionCMSSession extends SipSession {
  private long swigCPtr;

  protected SubscriptionCMSSession(long cPtr, boolean cMemoryOwn) {
    super(tinyWRAPJNI.SubscriptionCMSSession_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SubscriptionCMSSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tinyWRAPJNI.delete_SubscriptionCMSSession(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SubscriptionCMSSession(SipStack pStack) {
    this(tinyWRAPJNI.new_SubscriptionCMSSession(SipStack.getCPtr(pStack), pStack), true);
  }

  public boolean subscribeCMS(java.nio.ByteBuffer payload, long len, java.nio.ByteBuffer payload2, long len2, ActionConfig config) {
    return tinyWRAPJNI.SubscriptionCMSSession_subscribeCMS__SWIG_0(swigCPtr, this, payload, len, payload2, len2, ActionConfig.getCPtr(config), config);
  }

  public boolean subscribeCMS(java.nio.ByteBuffer payload, long len, java.nio.ByteBuffer payload2, long len2) {
    return tinyWRAPJNI.SubscriptionCMSSession_subscribeCMS__SWIG_1(swigCPtr, this, payload, len, payload2, len2);
  }

  public boolean unSubscribeCMS() {
    return tinyWRAPJNI.SubscriptionCMSSession_unSubscribeCMS(swigCPtr, this);
  }

}
