/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public class SubscriptionAffiliationEvent extends SipEvent {
  private long swigCPtr;

  protected SubscriptionAffiliationEvent(long cPtr, boolean cMemoryOwn) {
    super(tinyWRAPJNI.SubscriptionAffiliationEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SubscriptionAffiliationEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tinyWRAPJNI.delete_SubscriptionAffiliationEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public tsip_subscribe_event_type_t getType() {
    return tsip_subscribe_event_type_t.swigToEnum(tinyWRAPJNI.SubscriptionAffiliationEvent_getType(swigCPtr, this));
  }

  public SubscriptionAffiliationSession getSession() {
    long cPtr = tinyWRAPJNI.SubscriptionAffiliationEvent_getSession(swigCPtr, this);
    return (cPtr == 0) ? null : new SubscriptionAffiliationSession(cPtr, false);
  }

  public SubscriptionAffiliationSession takeSessionOwnership() {
    long cPtr = tinyWRAPJNI.SubscriptionAffiliationEvent_takeSessionOwnership(swigCPtr, this);
    return (cPtr == 0) ? null : new SubscriptionAffiliationSession(cPtr, true);
  }

}
