/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public class SubscriptionCMSEvent extends SipEvent {
  private long swigCPtr;

  protected SubscriptionCMSEvent(long cPtr, boolean cMemoryOwn) {
    super(tinyWRAPJNI.SubscriptionCMSEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SubscriptionCMSEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tinyWRAPJNI.delete_SubscriptionCMSEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public tsip_subscribe_event_type_t getType() {
    return tsip_subscribe_event_type_t.swigToEnum(tinyWRAPJNI.SubscriptionCMSEvent_getType(swigCPtr, this));
  }

  public SubscriptionCMSSession getSession() {
    long cPtr = tinyWRAPJNI.SubscriptionCMSEvent_getSession(swigCPtr, this);
    return (cPtr == 0) ? null : new SubscriptionCMSSession(cPtr, false);
  }

  public SubscriptionCMSSession takeSessionOwnership() {
    long cPtr = tinyWRAPJNI.SubscriptionCMSEvent_takeSessionOwnership(swigCPtr, this);
    return (cPtr == 0) ? null : new SubscriptionCMSSession(cPtr, false);
  }

}
