/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public class PublicationAffiliationSession extends SipSession {
  private long swigCPtr;

  protected PublicationAffiliationSession(long cPtr, boolean cMemoryOwn) {
    super(tinyWRAPJNI.PublicationAffiliationSession_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PublicationAffiliationSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tinyWRAPJNI.delete_PublicationAffiliationSession(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PublicationAffiliationSession(SipStack pStack) {
    this(tinyWRAPJNI.new_PublicationAffiliationSession(SipStack.getCPtr(pStack), pStack), true);
  }

  public boolean publish(java.nio.ByteBuffer payload, long len, ActionConfig config) {
    return tinyWRAPJNI.PublicationAffiliationSession_publish__SWIG_0(swigCPtr, this, payload, len, ActionConfig.getCPtr(config), config);
  }

  public boolean publish(java.nio.ByteBuffer payload, long len) {
    return tinyWRAPJNI.PublicationAffiliationSession_publish__SWIG_1(swigCPtr, this, payload, len);
  }

  public boolean unPublish(java.nio.ByteBuffer payload, long len, ActionConfig config) {
    return tinyWRAPJNI.PublicationAffiliationSession_unPublish__SWIG_0(swigCPtr, this, payload, len, ActionConfig.getCPtr(config), config);
  }

  public boolean unPublish(java.nio.ByteBuffer payload, long len) {
    return tinyWRAPJNI.PublicationAffiliationSession_unPublish__SWIG_1(swigCPtr, this, payload, len);
  }

}
